// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesAPI.Data;

#nullable disable

namespace QuotesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuotesAPI.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Steve Jobs",
                            Category = "Motivación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "El único modo de hacer un gran trabajo es amar lo que haces."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Albert Einstein",
                            Category = "Motivación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "En medio de la dificultad reside la oportunidad."
                        },
                        new
                        {
                            Id = 3,
                            Author = "John Lennon",
                            Category = "Vida",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "La vida es lo que pasa mientras estás ocupado haciendo otros planes."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert C. Martin",
                            Category = "Programación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "El código limpio siempre parece escrito por alguien a quien le importa."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Kent Beck",
                            Category = "Programación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Primero hazlo funcionar, luego hazlo correcto."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Leonardo da Vinci",
                            Category = "Vida",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "La simplicidad es la máxima sofisticación."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Albert Einstein",
                            Category = "Motivación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "No es que sea muy inteligente, es que paso más tiempo con los problemas."
                        },
                        new
                        {
                            Id = 8,
                            Author = "John Wayne",
                            Category = "Sabiduría",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Habla bajo, habla despacio y no digas demasiado."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Martin Fowler",
                            Category = "Programación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Cualquier idiota puede escribir código que una computadora entienda. Los buenos programadores escriben código que los humanos pueden entender."
                        },
                        new
                        {
                            Id = 10,
                            Author = "Peter Drucker",
                            Category = "Motivación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "La mejor forma de predecir el futuro es crearlo."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Oscar Wilde",
                            Category = "Vida",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "La experiencia es el nombre que todos damos a nuestros errores."
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ralph Johnson",
                            Category = "Programación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Antes de que el software pueda ser reutilizable primero tiene que ser utilizable."
                        },
                        new
                        {
                            Id = 13,
                            Author = "Muhammad Ali",
                            Category = "Motivación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "No cuentes los días, haz que los días cuenten."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Confucio",
                            Category = "Vida",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "La vida es realmente simple, pero insistimos en hacerla complicada."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Rick Cook",
                            Category = "Programación",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Programar hoy es una carrera entre los ingenieros de software que intentan construir programas más grandes y mejores, y el universo intentando producir idiotas más grandes. Hasta ahora, el universo está ganando."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
